### ISSUE TITLE
tool.zip被windows defender报毒

### ISSUE THREAD

**Issue by jm33-m0** [HostsTools/Windows#21]
windows对修改%systemroot%下文件的操作都很敏感，建议使用powershell脚本或batch完成敏感操作

**Comment by ghost** [comment]
我似乎有在readme中讲过 杀毒软件敏感吧…
报毒不是是正常的事情吗……更何况是修改敏感的hosts文件 如果不报毒杀毒软件才是有问题吧

-------- Original message --------

**Comment by jm33-m0** [comment]
哈哈。确实。。不过用脚本实现就没有提示了

**Comment by jm33-m0** [comment]
另外报毒是在下载的时候，也就是说你的程序进了微软的病毒库。。

**Comment by ghost** [comment]
别人用了之后 defender上传 然后微软发现有修改hosts 重定向到非法网站 那肯定把这个特征ban了阿……
脚本没有报毒 说明它太low 而且坦白说 这个杀毒软件不适合在国内使用

-------- Original message --------

**Comment by jm33-m0** [comment]
。。可能是因为我对所有ps脚本开了信任

**Comment by ghost** [comment]
是啊 那你都这样说 还有什么话讲。。。

**Comment by jm33-m0** [comment]
昨天把它转成exe以admin身份运行，还是没有报警

**Comment by ghost** [comment]
万一exe也是释放一个ps脚本之后 然后运行呢
且不说这个 有可能windows defender对bat vbs ps脚本都没有查杀能力 是否这个也是一个问题呢
倘若知识bat文件的话 原项目链接就已经有这种bat脚本了。。所以为何不去用呢。。
这个exe是解决在大部分情况下bat可能出现的问题
最后一点 稍有常识的人都知道 修改hosts文件 杀毒软件不报错 就是杀毒软件垃圾 就算我用bat脚本 360之类的国产杀毒软件都会报毒 那用户还需要添加两个验证 何必因为其中一个特例儿修改源代码呢 windows defender同样可以用添加例外来解决这个所谓的报毒问题

**Comment by jm33-m0** [comment]
想起来了。。第一次修改hosts的时候我对修改hosts的行为开了信任。。

确实，这个操作会让安全软件报警，但是整个程序进入特征库也不太好。。

**Comment by ghost** [comment]
特征库啊 那没有办法的  总有智障杀毒软件把编译的东西当作是病毒
