### ISSUE TITLE
【BUG Report】程序异常退出

### ISSUE THREAD

**Issue by LightSofa** [HostsTools/Windows#23]
![2016-09-02_130045](https://cloud.githubusercontent.com/assets/2208855/18193150/55705f88-710d-11e6-9361-9d55559e9fd6.png)

**Comment by ghost** [comment]
您是否有多次尝试…

**Comment by LightSofa** [comment]
@Too-Naive 试过几次的..

**Comment by ghost** [comment]
您还有没有其他的联络方式…mail不太方便debug

**Comment by LightSofa** [comment]
@Too-Naive 我的QQ：1715611987

**Comment by ghost** [comment]
好的 稍等一会联系您

Sent from my Mi phone
On LightSofa notifications@github.com, Sep 6, 2016 6:56 PM wrote:

@Too-Naivehttps://github.com/Too-Naive 我的QQ：1715611987

**Comment by ghost** [comment]
commit more error information may can help solve this problem

**Comment by sunshine-demo** [comment]
这个最后怎么解决了啊，我也出现这个问题了。
![image](https://ituku.tk/di/JPC7V/-e-.png)

**Comment by ghost** [comment]
@lv896391 防毒软件的问题
