### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by rcyggdra** [HostsTools/Windows#24]
每次通过双击tool更新头部总会有一行空白，更新几次后hosts多了很多空行。

**Comment by ghost** [comment]
感谢反馈… 历史遗留问题
会在下个版本修复 谢谢

**Comment by sihebi** [comment]
下载后防病毒软件Symantec endpoint会报病毒，并直接删掉，报Trojan.Gen.2威胁。这个是什么原因呢？

**Comment by ghost** [comment]
@sihebi #25 #21
