### ISSUE TITLE
现在打开会被杀软禁用了

### ISSUE THREAD

**Issue by yerphon** [HostsTools/Windows#25]
提示_tfopen() Error!

**Comment by ghost** [comment]
请问是最新版本吗

On GeekZhe notifications@github.com, Oct 11, 2016 7:03 AM wrote:

提示_tfopen() Error!

**Comment by yerphon** [comment]
对，最新版，Windows Defender直接把它删了。

**Comment by ghost** [comment]
正常啊 禁用wd即可

On GeekZhe notifications@github.com, Oct 11, 2016 7:51 AM wrote:

对，最新版，Windows Defender直接把它删了。

**Comment by yerphon** [comment]
360和wd都关闭了，然后管理员权限运行，提示：
CopyFile() Error on copy hosts file to system path(GetLastError():2)

**Comment by ghost** [comment]
重新运行一次试试？

**Comment by c9mmand** [comment]
Windows Defender直接杀，能解决吗？又不想关闭Windows Defender，只有这一个杀软。

**Comment by ghost** [comment]
除了添加信任没有别的办法

On wuxiao2522 notifications@github.com, Oct 12, 2016 10:51 AM wrote:

Windows Defender直接杀，能解决吗？又不想关闭Windows Defender，只有这一个杀软。
