### ISSUE TITLE
FindFirstFile() Error!(2)

### ISSUE THREAD

**Issue by chucklu** [HostsTools/Windows#26]
Start replace hosts file:
 Step1:Download hosts file...        Done.
 Step2:Change Line Endings...        Done.

 Finish:Hosts file Not update.

**Comment by chucklu** [comment]
刚解压出来的时候，被microsoft security essentials查杀，直接删除了
现在已经允许这个项目了，但是打开之后，这个错误看不懂

可以在哪里看日志吗？

**Comment by chucklu** [comment]
奇怪，我运行choose.exe，选了1
又可以正常运行了，没提示错误

不过，还是不能访问谷歌

**Comment by chucklu** [comment]
尴尬，貌似又能访问谷歌，真是什么鬼

多谢你的工具

**Comment by ghost** [comment]
允许之后就没有问题了吗...

**Comment by chucklu** [comment]
@Too-Naive   现在没问题了，刚开始还是不能访问谷歌。不太搞得懂
已经可以正常使用了

**Comment by ghost** [comment]
正常运行还有问题吗...我需要了解这个

**Comment by chucklu** [comment]
什么意思啊，你说的正常运行，指什么？

**Comment by ghost** [comment]
没有任何错误提示 就是正常运行

**Comment by chucklu** [comment]
现在恢复正常了，没问题了。
之前那个错误  Error!(2) 
这个是是啥意思呢

**Comment by ghost** [comment]
ERROR_FILE_NOT_FOUND

**Comment by chucklu** [comment]
哦，记得我还操作了一个reset，通过choose.exe。
     5. Reset Hosts File(Set to Default Hosts File)
应该是操作这个之后，再运行1.Run normaly   才恢复的

另外说一下，我之前，一直用的是tools里面的bat脚本。
今天发现之前的不能用，就找了最新的

**Comment by ghost** [comment]
噢噢....谢谢您的反馈

**Comment by chucklu** [comment]
注意事项里的第4个
请间隔一段时间后清理%SystemRoot%\system32\drivers\etc\文件夹 (程序加入了询问删除早期备份文件的功能)

这个询问删除早起备份文件的功能，在哪里啊？我似乎没有看到呢

**Comment by ghost** [comment]
您运行了足够多次数之后 就能看到啦(笑
备份文件至少要有20个才会触发这个条件(你可以复制几个试试

**Comment by chucklu** [comment]
@Too-Naive 
在我的etc目录下，发现好多文件备份：
有2种格式的
第一种
hosts_2016-03-24_周四_12-15-06.bak
第二种
hosts.20161014.143235.bak

第一种备份格式，应该是以前的bat脚本文件运行生成的，有90多个了。一直没清除
第二种备份格式，是tool.exe今天生成的，目前只有2个

能让程序兼容第一种备份格式吗？
你以什么标准作为备份识别的？

**Comment by ghost** [comment]
备份是整个文件直接备份. 前面那种备份我并没有研究过是什么情况= =
备份只是为了以防万一 如程序出错的话可以用备份来还原 这样

**Comment by chucklu** [comment]
@Too-Naive 我知道备份的作用
你清除备份的时候，可以用.bak后缀，作为判断标准吗？

**Comment by ghost** [comment]
https://github.com/HostsTools/Windows/blob/92da869ee3bbcf836a3bc875728e263da555f0b9/tool.cpp#L940

**Comment by chucklu** [comment]
@Too-Naive 
C++的代码？我不太能看懂
你能把.bak作为删除备份的标准吗？

**Comment by ghost** [comment]
可以是可以 修改一下即可

On Chuck Lu notifications@github.com, Oct 17, 2016 11:15 AM wrote:

@Too-Naivehttps://github.com/Too-Naive
C++的代码？我不太能看懂
你能把.bak作为删除备份的标准吗？

**Comment by chucklu** [comment]
那就期待了，目前来看，似乎只有你的.bak备份文件。
如果担心和别人的冲突的话，你可以自己建一个文件夹来存放备份。
文件夹的名字，唯一识别，就可以了

**Comment by ghost** [comment]
实际上是`hosts.20*.bak`通配符来识别的

**Comment by chucklu** [comment]
哦，以前的版本是带下划线的
