### ISSUE TITLE
腾讯电脑管家报毒

### ISSUE THREAD

**Issue by j717273419** [HostsTools/Windows#30]
腾讯直接报木马那个tool.exe文件

**Comment by ghost** [comment]
正常..... #25 #21

**Comment by CHN008** [comment]
用这些娱乐软件最好不要FQ,你的隐私和安全没保障. :smile_cat:

**Comment by ghost** [comment]
@CHN008 我听说某数字软件和防火墙有勾当
刚才忘记打码了
![](https://cloud.githubusercontent.com/assets/16496671/20400129/79eea6b4-ad2e-11e6-9aba-2f4cbf83dc08.png)

**Comment by CHN008** [comment]
嗯,看过网上的新闻,方狗还有华为都对那个qiang有"贡献"

**Comment by ghost** [comment]
没办法的事 说不定就是他们的锅

**Comment by sunshine-demo** [comment]
chrome下载也直接说是恶意软件。。

**Comment by ghost** [comment]
@lv896391 https://github.com/racaljk/hosts/issues/803#issuecomment-260643575

**Comment by ghost** [comment]
其实基本上下一个版本就好了。。不一定要更新到最新版本
原来的版本有问题或者确实需要新功能的话再更新也不迟..

**Comment by BROBIRD** [comment]
@Too-Naive 这个图……怎么好像看起来似曾相识啊= =🌚

**Comment by ghost** [comment]
#33
