### ISSUE TITLE
从16日开始无法正常更新host

### ISSUE THREAD

**Issue by outranger** [HostsTools/Windows#31]
host里和备份的.bak文件里`# Copyright (c) 2014-2016, racaljk.`
之后的内容变成
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" name="viewport" id="viewport">
    <title>404 Not Found</title>
    <style type="text/css">
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            background-color: #000;
            font-family: "PingFang SC", "Helvetica Neue", "Hiragino Sans GB", "Segoe UI", "Microsoft YaHei", "微软雅黑", sans-serif;
            overflow: hidden;
        }
        h1, div, p, a {
            color: #fff;
        }
        a {
            text-decoration: none;
        }
        .circle {
            height: 100px;
            width: 100px;
            display: inline-block!important;
            border-radius: 100px;
            background-color: #fdfdfe;
            float: right;
            margin-top: 260px;
        }
        .forgive {
            color: #262626;
            font-size: 14px;
            display: block;
            width: 60px;
            margin-top: 27px;
            margin-left: 23px;
        }
        .eye {
            background-color: #262626;
            height: 20px;
            width: 20px;
            display: inline-block!important;
            border-radius: 20px;
            position: relative;
        }
    </style>
</head>

<body>
<div style="width: 960px; margin: 10% auto">
    <div style="width: 40%;float: left">
        <div class="eye" style="left: 125px; top: -140px"></div>
        <div class="eye" style="left: 250px; top: -140px"></div>
        <img src="https://dn-coding-net-production-static.qbox.me/static/4fed99a3dc1af35300cc96113ba332bb.png" alt="404 Not Found" style="width: 85%">
    </div>
    <div style="float: left; color: #000; width: 60%">
        <div style="margin-left: 50px">
            <div style="font-size: 500%">404!</div>
            <div style="font-size: 150%">页面，我找不到你，我找不到你啊~</div>
        </div>
    </div>
    <div class="circle">
        <a href="https://coding.net/"><span class="forgive" style="margin-top:38px">返回首页</span></a>
    </div>
</div>
</body>
</html>
这样重复的html。
我手动重新更新host，再运行hostool还是这样。是服务器挂了？

**Comment by dongshilang** [comment]
同样遇到这个问题

**Comment by outranger** [comment]
@dongshilang 在host那边有->[#802](https://github.com/racaljk/hosts/issues/802)，重新下一遍tools就好了

**Comment by ghost** [comment]
请更新
