### ISSUE TITLE
下载的exe被chrome和mse都报病毒杀掉了，后来

### ISSUE THREAD

**Issue by cathaychen** [HostsTools/Windows#33]
下载的exe被chrome和mse都报病毒杀掉了，后来下载代码自己编译，哎，好了，一口气能上六楼

**Comment by ghost** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
然而似乎并没有办法？ 要不要写个编译教程什么的...

**Comment by BROBIRD** [comment]
@cathaychen 腰不酸腿不疼了（大雾）

**Comment by ghost** [comment]
windows defender 直接杀害之

**Comment by cathaychen** [comment]
编译还是挺简单的，vs和codeblock+mingw均编译成功

**Comment by ghost** [comment]
或许有的人不会编译？

**Comment by cathaychen** [comment]
@Too-Naive 应该是会有

**Comment by ghost** [comment]
那就加个教程吧 反正不碍事XD

**Comment by BROBIRD** [comment]
@Too-Naive 做个一键脚本也行

**Comment by cathaychen** [comment]
@Too-Naive   我也是个懒人。
如果是用VS2013、VS2015的话，代码中有项目文件，我是用vs2005，自己建个项目，把tool.cpp和那几个头文件加进去就可以了

**Comment by theratlesnake** [comment]
求解决方法，下载就被谷歌浏览器禁止了

**Comment by ghost** [comment]
一个是临时关掉
![](https://cloud.githubusercontent.com/assets/16496671/22403292/c7317c28-e64d-11e6-9c67-8b7762861a54.png)
另外可以自行安装编译器来编译

**Comment by theratlesnake** [comment]
谢谢谢谢！还有个问题请教一下，有些网站，例如https://program-think.blogspot.com/ 编程思想的博客怎么打开呢？是不是要手动添加hosts？

**Comment by ghost** [comment]
是的 在某个commit中我们把它删掉了 原因你懂的

**Comment by theratlesnake** [comment]
不太懂啊，本人菜鸟一个，另外，请问下，如果要添加他的博客到hosts，具体怎么弄，可以教教吗？

**Comment by ghost** [comment]
https://github.com/racaljk/hosts/issues/529

**Comment by theratlesnake** [comment]
请问一下，有什么办法可以把一个网站的ip地址找出来，然后自己添加到hosts里吗？

**Comment by ghost** [comment]
或许您可以找找原项目里面有关的issue

**Comment by theratlesnake** [comment]
你不是创建人吗？老大

**Comment by ghost** [comment]
不是啊....... https://github.com/racaljk/hosts/search?q=%E6%9F%A5%E6%89%BEip&type=Issues&utf8=%E2%9C%93

**Comment by theratlesnake** [comment]
谢谢
