### ISSUE TITLE
host tool 运行下载最新的host文件失败啊，为什么呢

### ISSUE THREAD

**Issue by ScalletLeng** [HostsTools/Windows#34]
host tool 运行下载最新的host文件失败啊，为什么呢

**Comment by ghost** [comment]
运行截图?

**Comment by ScalletLeng** [comment]
![2016-12-12_142824](https://cloud.githubusercontent.com/assets/16712529/21090025/dbde0598-c077-11e6-9288-ab1b8c28edb5.png)

**Comment by cathaychen** [comment]
你要用管理员权限运行

**Comment by cathaychen** [comment]
右键菜单，选择以管理员身份运行

**Comment by cathaychen** [comment]
你的错误截图，似乎是不能访问网络的征兆

**Comment by ScalletLeng** [comment]
我刚刚试了管理员身份运行也不行。我能访问网络啊，不然怎么回复的

**Comment by ScalletLeng** [comment]
![2016-12-12_145640](https://cloud.githubusercontent.com/assets/16712529/21090511/3ce14f96-c07b-11e6-951b-c533254d50a1.png)

**Comment by ghost** [comment]
看起来你的版本比较早了…尝试更新一下程序的版本…在release页面有
然后是 确定没有什么杀毒软件的干预吗？

**Comment by ghost** [comment]
@cathaychen 强制使用管理员权限运行的(只要是我预编译的版本 或者用该工程下VS的编译文件编译的版本 或者使用`g++make.bat`脚本编译的版本)

**Comment by cathaychen** [comment]
@Too-Naive 我自己编译的，不能强制以管理员身份运行，我没用你的VS的编译文件，因为我是用vs2005，另外我用code::blocks+mingw32编译的也是不强制使用管理员权限运行的，应该是跟我建立的工程有关吧，没有设置。我说我编译的应用程序怎么比你提供的要小呢。

**Comment by cathaychen** [comment]
@Too-Naive OK，我用CodeBlocks重新编译了一把，加上了强制使用管理员权限，OK了

**Comment by ghost** [comment]
@cathaychen 2005那个时候貌似还没有权限这一说?

**Comment by cathaychen** [comment]
@Too-Naive 是的，2005并不支持支持UAC的设置，如果要加权限，需要像g++一样加上manifest清单文件来实现

**Comment by cathaychen** [comment]
@Too-Naive 
![1](https://cloud.githubusercontent.com/assets/12231799/21129551/2c3d2ed6-c13d-11e6-8f5c-c63c9f217efd.png)

**Comment by ghost** [comment]
OKOK



On cathaychen <notifications@github.com>, Dec 13, 2016 14:05 wrote:

@Too-Naive<https://github.com/Too-Naive>
[1]<https://cloud.githubusercontent.com/assets/12231799/21129551/2c3d2ed6-c13d-11e6-8f5c-c63c9f217efd.png>
