### ISSUE TITLE
最新版本报毒

### ISSUE THREAD

**Issue by stonedreamforest** [HostsTools/Windows#35]
RT 各大浏览器阻止下载

**Comment by Too-Naive** [comment]
hhhh 详见各issue 这里不一一列举了

**Comment by stonedreamforest** [comment]
........我有个以前版本的不报毒 我还是将就用吧

**Comment by Too-Naive** [comment]
= =所有以前的版本都能下载到 你可以再试试看看会不会报毒 https://github.com/HostsTools/Windows/releases

**Comment by Too-Naive** [comment]
那你很棒噢

**Comment by Too-Naive** [comment]
你要是脑袋有坑 出门左拐有coding.net 不要来github丢脸
github不缺你这种废物
