### ISSUE TITLE
我觉得你这个人很偏激 真的是有浆糊 煞笔

### ISSUE THREAD

**Issue by stonedreamforest** [HostsTools/Windows#36]
煞笔

**Comment by stonedreamforest** [comment]
煞笔 再说一次 煞笔
上个gitub还能给你激动的区分人群

那你很棒噢  噢  噢  噢  噢  噢  噢  你个煞笔 

是不是觉得自己说这句话乖萌乖萌乖萌的 

神经质煞笔

**Comment by Too-Naive** [comment]
那你tm很棒咯 废物要我给你鼓掌吗？

**Comment by Too-Naive** [comment]
老子tm做个程序给你用你tm还直接爆粗是吧 那你是真的他妈牛逼咯 你父母没教你怎么做人是吧 那是不是要我来教你做人啊？
一句操你妈送给你 怎么 不开心吗？ 操你妈 爽了？
