### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by 20161223** [HostsTools/Windows#37]
煞笔

 先不说别的 就说骂人 谁内心肮脏 接收到推送的心里明白。 我就不说

煞笔  

我说你脑子有浆糊 
我分明说我用我以前用的一个版本好了 你还煞笔发上来要我编译 是不是有浆糊

真尼玛傻缺啊 不服不行

说句浆糊 你什么话都说的出口   一下萌萌哒 一下残废 你说你不是神经质是啥

我看你是混贴吧混微博混多了  学了些自以为是词语

就算用也得分场合  

又想当婊子又想列贞节牌坊

low逼得不要不要的

做一个dowloadfile也能嗨上天  

什么妈啊废物挂嘴边像说顺口溜一样 

习以为常了吧

 戾气重不行

会用权限了不起啊 我注册小号不就是了 真是服了 

这尼玛还要权限我

你骂人不像是加特林一样 怎么还要权限我 

说骂人 

我是骂不过

但是性子好啊  我闲着没事就过来跟你交流下

你倒是咬我啊 

权限我啊 

煞笔
![3](https://cloud.githubusercontent.com/assets/16742566/21431493/76981380-c8a2-11e6-9f75-5eebfe0fc020.png)

**Comment by Too-Naive** [comment]
所以你是像好好说话的态度？ 我没有跟你再好好说话？
我只是想让你试试以前的版本下载会不会再报毒而已你自己是什么口气自己心里不清楚？
就算你不要你不要就不要啊 混微博多的人是你吧 你自己不愿意做的事情我又没强求又求着你去做 然后所以这就是你进行人身攻击的理由？

如果你误会了我原来的意思 那么我现在跟你解释清楚了 你不愿去做的事情没人愿意强求你去做 
# 所以谁他妈先开口爆粗然后现在圣人婊了？

**Comment by Too-Naive** [comment]
编译过的二进制文件都在那里我有求着你编译了？ 我tm跪着求你说要编译了？

# 圣人婊就是厉害啊 谁一定要跟你讲理啊 狗咬我我还要忍着被咬了？

**Comment by Too-Naive** [comment]
服气

**Comment by Too-Naive** [comment]
有本事随便给别人看看到底是谁不讲理啊 自己先开口骂人脑子有浆糊还真他妈有脸了

**Comment by Too-Naive** [comment]
药店碧莲

**Comment by Too-Naive** [comment]
睡觉之前再说一句 我没有时间跟你在这里扯皮 你要去扯皮你去微博 去知乎扯皮去
在我看来 我在做事情做得非常烦躁的时候 莫名其妙被人骂我还要很开心了？
你自己看看自己repo都是什么 还不都是fork来的？自己有写出什么吗？
你要是能做得比我厉害 那么欢迎你提交pull request我来合并到项目里面 如果不行 那你还来这里bb什么

所以你就是硬要跟我咬文嚼字咯 你先爆的粗口 反倒是我不对咯？呵呵。
