### ISSUE TITLE
[feature-request] silent模式

### ISSUE THREAD

**Issue by luboq** [HostsTools/Windows#41]
更新完了，必须点一次，才能退出
希望加个启动参数，-s        silent模式  完全后台运行就好了

可能有朋友说，安装后台更新服务，就能在后台默默更新了
但个人不愿意，半小时运行一次……
加了silent模式，多方便啊

参考cow项目：https://github.com/cyfdecyf/cow
不但提供了cow.exe，还有
• cow-taskbar.exe，隐藏到托盘执行
• cow-hide.exe，隐藏为后台程序执行

**Comment by ghost** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)这个简单 不过作者弃坑了 怎么办(

**Comment by ghost** [comment]
其实可以把messagebox那一行删掉就好了(

**Comment by luboq** [comment]
是[#L820](https://github.com/HostsTools/Windows/blob/redirect/tool.cpp#L820)这行msgbox吗？
不过我电脑上没VC啊…还得编译…算了懒得折腾了:_wacko:

**Comment by ghost** [comment]
@waldens 需要的话等下我直接重新编译上传上来好了…反正不碍事(

**Comment by luboq** [comment]
真不碍事吗？那就麻烦啦 谢谢💕  这样丢进启动文件夹里，就能开机更新一次了😙

**Comment by ghost** [comment]
Available in:https://github.com/HostsTools/Windows/releases/tag/v2.1.19
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)这破站不给我传zip 我只好扔在release里面

**Comment by ghost** [comment]
~~(忘记改日期了...容我改一下(逃~~
![](https://cloud.githubusercontent.com/assets/16496671/14747730/62dc54fc-08e8-11e6-8e09-12005c61b21b.jpg)算了= =太麻烦

**Comment by ghost** [comment]
不过我发现似乎还有这个东西... 不过我已经忘记当时怎么写的了... https://github.com/HostsTools/Windows#new-feature

**Comment by luboq** [comment]
@Too-Naive 谢谢，可以加进开机自启的脚本里啦，非常感谢！<img alt="ghe-emoji" title=":_onion_head_beg:" src="https://cloud.githubusercontent.com/assets/136959/13371098/94bc99e0-dce3-11e5-988e-bf322e6871c7.gif">
