### ISSUE TITLE
WD报tool毒

### ISSUE THREAD

**Issue by ertcds** [HostsTools/Windows#42]
![snipaste20170226_133936.png](https://ooo.0o0.ooo/2017/02/26/58b26a2e02d5e.png)
是因为修改host文件原因吗？

**Comment by Too-Naive** [comment]
#21

**Comment by jingouwangzi** [comment]
同样滴问题，下都下不下来

**Comment by Too-Naive** [comment]
(

**Comment by ddsdggsg** [comment]
先在电脑里建个新文件夹（目标下载位置），然后添加此文件夹路径进杀毒软件的“排除”列表，此文件夹内建议只存放信得过的文件。

**Comment by miku1958** [comment]
RS2的wd直接清除掉后，不让还原了........

**Comment by teraStars** [comment]
win10最新版同样问题。
