### ISSUE TITLE
 Reset Hosts File(Set to Default Hosts File)  is not working

### ISSUE THREAD

**Issue by chucklu** [HostsTools/Windows#43]
the program can not reset the hosts file to the default

**Comment by ghost** [comment]
Have you ever check the anti-virus program?

**Comment by chucklu** [comment]
yes,I am using microsoft security essentials.
It blocked the tool.exe,and I have recovered it.
I am trying to use  choose.exe to reset the hosts file

**Comment by chucklu** [comment]
maybe it is the problem of security essentials,I am checking again

**Comment by chucklu** [comment]
try to unzip another zip file，it's working now.
Not sure what the  security essentials did

**Comment by ghost** [comment]
It may prevent some software from internet to do something dangerous behaviour.
Try this:
- Open tool.zip properties
- Click Unblock
- Click OK
![image](https://cloud.githubusercontent.com/assets/16496671/23584641/ec32fed8-01a1-11e7-8895-d13247a20dbf.png)
It may be work

**Comment by chucklu** [comment]
not sure,I just uninstalled the Security Essential

**Comment by ghost** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)
