### ISSUE TITLE
download hosts file error (GetLastError():2)

### ISSUE THREAD

**Issue by chucklu** [HostsTools/Windows#45]
the choose.exe crash after met several "There seems something wrong in download file, we will retry after 5 seconds."
![qq 20170313170438](https://cloud.githubusercontent.com/assets/3004057/23847821/2773fcea-080f-11e7-9553-a9dc0c13feeb.jpg)

**Comment by ghost** [comment]
防毒软件?

**Comment by chucklu** [comment]
@Too-Naive 不知道，因为换了一台电脑，临时用的。我之前特意看的，貌似没有杀毒软件啊。
第一次遇到这个错误呢
之前杀毒软件的错误提示，不是这个啊

**Comment by ghost** [comment]
这就很奇怪了 可以正常上github吗

**Comment by chucklu** [comment]
@Too-Naive 似乎也不太正常，这个issue，是在那台电脑开的，但是图片传不了。edit也点不动
后来在自己电脑上弄的
 
代码里面，这个错误是什么情况下触发的啊？

**Comment by ghost** [comment]
就是网络原因.....

**Comment by chucklu** [comment]
@Too-Naive  那你的错误提示是啥意思，还有为啥程序会崩溃啊？没有处理这个异常吗？

**Comment by ghost** [comment]
>Fatal Error:
>Download hosts file Error!

这个不就是下载失败吗...一般情况下多试几次就好了
本来按照设计超过三次错误就直接崩溃退出了呀...我认为一直重试没有意义

**Comment by chucklu** [comment]
@Too-Naive 下载错误的话，有提示就可以。但是程序为啥要崩溃啊

**Comment by ghost** [comment]
![](https://cloud.githubusercontent.com/assets/16496671/20557321/f47b3c50-b1a5-11e6-8810-8edc50a65778.png)崩溃会比较显眼一些(?)

**Comment by chucklu** [comment]
@Too-Naive 有错误提示就可以了，把崩溃这个bug修复一下啊
我截图的时候，忘记截图那个崩溃的界面了。反正就是一个系统级的崩溃

**Comment by ghost** [comment]
讲道理我觉得崩溃没什么问题啊

**Comment by chucklu** [comment]
@Too-Naive 软件怎么能崩溃呢？虽然qq有崩溃，但是崩溃的时候，腾讯会提示发送bug报告，说明腾讯还是想修复崩溃的bug的

ps:我觉得这个应该属于软件的健壮性的话题吧，比如除以零，崩溃。要有容错机制的吧

**Comment by ghost** [comment]
https://github.com/HostsTools/Windows/blob/master/tool.cpp#L876
https://github.com/HostsTools/Windows/blob/master/tool.cpp#L994

**Comment by chucklu** [comment]
@Too-Naive  啥意思啊？我不懂C++的。你发的2个链接，跳转到具体代码了。不明白是干嘛的

**Comment by Riajyuu** [comment]
@chucklu 崩溃的意义在于：

1. 避免过多不必要的重试以避免强行拖累系统运行
2. 跳出死循环

**Comment by chucklu** [comment]
@EMLVIRUS   跳出死循环，为啥要导致程序崩溃呢？不明白是什么逻辑
C#程序里，跳出死循环，不会导致死循环的

**Comment by ghost** [comment]
重试三次已经很多了啊= =之所以用abort本来就是runtime error层面的事情啊...... 只要崩溃肯定就是runtime error 而不是程序本身的问题啊

**Comment by ghost** [comment]
或者这么说 本身没问题的时候都是正常的 之所以会崩溃 可能会引起用户的足够重视

**Comment by chucklu** [comment]
@Too-Naive 
还是理解不了，我的编程概念中，任何时候都不应该导致程序崩溃吧
有问题的话，捕获异常，写日志。然后根据日志来找错误

**Comment by Riajyuu** [comment]
这说明你是个假的程序员=。=

**Comment by chucklu** [comment]
@EMLVIRUS  C#的程序，如果没安装.net的话，貌似也会崩溃的。是系统级的。
不过，现在这个多次下载文件失败，也能导致系统级的崩溃？

**Comment by ghost** [comment]
那你说 程序下载不了hosts 程序还能做什么....

**Comment by chucklu** [comment]
@Too-Naive  下载不了，就给出错误提示啊。这就可以了啊

**Comment by ghost** [comment]
那我abort掉不行吗= =

**Comment by Riajyuu** [comment]
崩溃是正常设计行为，为了防止一个意料之外的错误导致更多错误
你不会是以为崩溃是设计缺陷吧？
PS : 情况都不可控了 你报错有毛用？就得强行结束，表现就是崩溃

**Comment by chucklu** [comment]
@EMLVIRUS  无法理解，崩溃怎么能算是正常设计行为啊。除非是系统导致的，不受控制的。
这个程序的情况，只是尝试下载文件失败了。那就给出错误提示啊
你说是情况不可控，指什么呢？我理解不了。我确实以为程序崩溃是代码的bug导致的

我的理解是可控的，下载三次失败，那就停止尝试。给出错误提示，这就结束了啊。

**Comment by Riajyuu** [comment]
OK
最后说明一次：
1. 崩溃是广泛用于所有编程语言的正常设计行为，绝非缺陷；无法理解就请你死记住=。=
2. 此例中，给出错误提示无法解决重试失败，重试失败过多无意义，只能强行终止。作为一个批处理集合，强行终止的唯一办法也是崩溃。

**Comment by Riajyuu** [comment]
忘了一句：系统导致的程序崩溃或者系统自身崩溃也是设计之内的行为。
对，你没看错，是故意的。

**Comment by chucklu** [comment]
@EMLVIRUS  不清楚C++是怎么处理的，不能弄一个计数吗？计数3次，给出提示。
这个很难吗？

**Comment by Riajyuu** [comment]
选择性无视？

> 此例中，给出错误提示无法解决重试失败，重试失败过多无意义，只能强行终止。作为一个批处理集合，强行终止的唯一办法也是崩溃。

**Comment by chucklu** [comment]
@EMLVIRUS 作为一个批处理集合，强行终止的唯一办法也是崩溃。
理解不了，为啥一定要用批处理集合呢？不能换一个方法？
用一个可以不崩溃的？

**Comment by Riajyuu** [comment]
@Too-Naive 请锁贴=。=
