### ISSUE TITLE
3.25 google限制了修改Host的chrome用户的更新，有办法解决么？

### ISSUE THREAD

**Issue by taburiss4869** [HostsTools/Windows#48]
提示
检查更新时出错：由于在此国家/地区的访问权限遭到限制，安装失败。（错误代码为： 7: 0x80040806 -- system level）
如果用贵工具修改了host挂代理也没用，只能恢复默认。。。。。

**Comment by ghost** [comment]
https://github.com/racaljk/hosts/issues/1036

**Comment by ghost** [comment]
總結：用代理即可
