### ISSUE TITLE
谷歌搜索不能用了啊

### ISSUE THREAD

**Issue by krokyhui** [HostsTools/Windows#50]
谷歌搜索这几天开始一直不能用了，推特脸书谷歌邮箱什么的都可以用，唯独谷歌搜索没法用了，是hosts失效么还是别的原因？？哦对了还有youtube能打开但是不能播放，这个是我网的问题么。。

**Comment by ghost** [comment]
https://github.com/racaljk/hosts/issues
racaljk/hosts#297
