### ISSUE TITLE
如何配置不需要覆盖的条目

### ISSUE THREAD

**Issue by dreamerisdoer** [HostsTools/Windows#53]

**Comment by ghost** [comment]
> 现在，可以在hosts的头部加上自定义的hosts，程序自动更新时不会覆盖掉自定义的hosts.例如
>```
>	127.0.0.1 baidu.com
>	127.0.0.1 www.baidu.com
>	# Copyright (c) 2014-2016, racaljk.
>	# https://github.com/racaljk/hosts
>```
>程序不会将第一行过滤掉，而会从`# Copyright (c) 2014-2016, racaljk.`开始改写hosts文件。
>
>如需忽略空行以及注释 请使用`choose.exe`打开`.ini`文件修改`false`为`true`
