### ISSUE TITLE
windows defender 报毒

### ISSUE THREAD

**Issue by Ashyoumo** [HostsTools/Windows#54]
trojan:win32/Dynamer!ac

**Comment by RocWu** [comment]
windows defender 报毒 Chrome 下载直接拦截

**Comment by jeddah-liu** [comment]
Same as above.
The tool.exe is report by Microsoft Security Essential as a trojan:win32/Dynamer!ac. 
May I read the Trojan report by the means that the tool.exe is trying to modify system host file?
Because it will backup the original host file and create a new one with address across the GFW.

**Comment by ghost** [comment]
@jeddah-liu Yes, most antivirus software believe that edit hosts is dangerous action.
