### ISSUE TITLE
你的hosts工具我用了几次都没用。请你改进

### ISSUE THREAD

**Issue by embeddedsecurity** [HostsTools/Windows#55]
你的hosts工具我用了几次都没用。请你改进。系统xp，谷歌浏览器。已经刷新dns。

**Comment by ghost** [comment]
請詳細說明什麼是沒用 你說沒用有很多種方面 是hosts沒有更新進去 還是無法打開網頁 單單說一個沒用 沒法描述問題 如果你不知道怎么提问 请去看提问的艺术 谢谢。

**Comment by xiaolongyuan** [comment]
这种人连话都不会说 理他作甚

**Comment by ghost** [comment]
@xiaolongyuan (
