### ISSUE TITLE
笑哭了 笑哭

### ISSUE THREAD

**Issue by WangGang1176034883** [HostsTools/Windows#63]
2017/05/14 06:47:57 Open log file.
2017/05/14 06:47:57 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/14 06:48:57 Start replace hosts file.
2017/05/14 06:48:58 Replace File Successfully
2017/05/14 07:19:02 Start replace hosts file.
2017/05/14 07:19:03 Finish:Hosts file Not update.

2017/05/14 07:49:03 Start replace hosts file.
2017/05/14 07:49:03 Finish:Hosts file Not update.

2017/05/14 08:19:03 Start replace hosts file.
2017/05/14 08:19:06 Finish:Hosts file Not update.

2017/05/14 08:49:06 Start replace hosts file.
2017/05/14 08:49:12 Finish:Hosts file Not update.

2017/05/14 09:19:12 Start replace hosts file.
2017/05/14 09:19:14 Finish:Hosts file Not update.

2017/05/14 09:49:14 Start replace hosts file.
2017/05/14 09:49:15 Finish:Hosts file Not update.

2017/05/14 10:19:15 Start replace hosts file.
2017/05/14 10:19:16 Finish:Hosts file Not update.

2017/05/14 10:49:16 Start replace hosts file.
2017/05/14 10:49:17 Finish:Hosts file Not update.

2017/05/14 11:19:17 Start replace hosts file.
2017/05/14 11:19:18 Finish:Hosts file Not update.

2017/05/14 12:20:18 Start replace hosts file.
2017/05/14 12:20:19 Finish:Hosts file Not update.

2017/05/14 13:21:19 Start replace hosts file.
2017/05/14 13:21:20 Finish:Hosts file Not update.

2017/05/14 14:22:20 Start replace hosts file.
2017/05/14 14:23:04 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.
2017/05/14 15:24:04 Start replace hosts file.
2017/05/14 15:24:05 Finish:Hosts file Not update.

2017/05/14 16:25:05 Start replace hosts file.
2017/05/14 16:25:07 Finish:Hosts file Not update.

2017/05/14 16:55:07 Start replace hosts file.
2017/05/14 16:55:07 Finish:Hosts file Not update.

2017/05/14 17:25:07 Start replace hosts file.
2017/05/14 17:25:14 Finish:Hosts file Not update.

2017/05/14 17:55:14 Start replace hosts file.
2017/05/14 17:55:15 Finish:Hosts file Not update.

2017/05/14 18:25:15 Start replace hosts file.
2017/05/14 18:25:27 Finish:Hosts file Not update.

2017/05/14 19:31:30 Start replace hosts file.
2017/05/14 19:31:37 Finish:Hosts file Not update.

2017/05/14 20:02:31 Open log file.
2017/05/14 20:02:31 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/14 20:03:31 Start replace hosts file.
2017/05/14 20:04:14 Finish:Hosts file Not update.

2017/05/14 20:34:14 Start replace hosts file.
2017/05/14 20:34:16 Finish:Hosts file Not update.

2017/05/14 21:04:16 Start replace hosts file.
2017/05/14 21:04:17 Finish:Hosts file Not update.

2017/05/14 21:34:17 Start replace hosts file.
2017/05/14 21:34:18 Finish:Hosts file Not update.

2017/05/14 22:04:18 Start replace hosts file.
2017/05/14 22:04:19 Finish:Hosts file Not update.

2017/05/14 22:34:19 Start replace hosts file.
2017/05/14 22:34:32 Finish:Hosts file Not update.

2017/05/14 23:04:32 Start replace hosts file.
2017/05/14 23:04:33 Finish:Hosts file Not update.

2017/05/14 23:34:33 Start replace hosts file.
2017/05/14 23:34:36 Finish:Hosts file Not update.

2017/05/14 23:45:22 Open log file.
2017/05/14 23:45:22 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/14 23:46:22 Start replace hosts file.
2017/05/14 23:46:23 Finish:Hosts file Not update.

2017/05/15 07:40:02 Open log file.
2017/05/15 07:40:02 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 07:41:02 Start replace hosts file.
2017/05/15 07:41:14 Replace File Successfully
2017/05/15 08:11:16 Start replace hosts file.
2017/05/15 08:11:17 Finish:Hosts file Not update.

2017/05/15 08:41:17 Start replace hosts file.
2017/05/15 08:41:18 Finish:Hosts file Not update.

2017/05/15 09:11:18 Start replace hosts file.
2017/05/15 09:11:18 Finish:Hosts file Not update.

2017/05/15 09:41:18 Start replace hosts file.
2017/05/15 09:41:19 Finish:Hosts file Not update.

2017/05/15 10:11:19 Start replace hosts file.
2017/05/15 10:11:20 Finish:Hosts file Not update.

2017/05/15 10:41:20 Start replace hosts file.
2017/05/15 10:41:21 Finish:Hosts file Not update.

2017/05/15 11:11:21 Start replace hosts file.
2017/05/15 11:11:22 Finish:Hosts file Not update.

2017/05/15 12:12:22 Start replace hosts file.
2017/05/15 12:12:22 Finish:Hosts file Not update.

2017/05/15 12:45:27 Open log file.
2017/05/15 12:45:27 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 17:03:54 Open log file.
2017/05/15 17:03:54 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 17:04:54 Start replace hosts file.
2017/05/15 17:04:55 Finish:Hosts file Not update.

2017/05/15 17:10:06 Open log file.
2017/05/15 17:10:06 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 17:11:06 Start replace hosts file.
2017/05/15 17:11:07 Finish:Hosts file Not update.

2017/05/15 17:12:56 Open log file.
2017/05/15 17:12:56 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 17:13:56 Start replace hosts file.
2017/05/15 17:13:57 Finish:Hosts file Not update.

2017/05/15 18:41:05 Start replace hosts file.
2017/05/15 18:41:06 Finish:Hosts file Not update.

2017/05/15 18:57:27 Open log file.
2017/05/15 18:57:27 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 18:58:27 Start replace hosts file.
2017/05/15 18:58:28 Finish:Hosts file Not update.

2017/05/15 19:09:19 Open log file.
2017/05/15 19:09:19 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 19:10:19 Start replace hosts file.
2017/05/15 19:10:20 Finish:Hosts file Not update.

2017/05/15 19:54:27 Open log file.
2017/05/15 19:54:27 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 19:55:27 Start replace hosts file.
2017/05/15 19:55:28 Finish:Hosts file Not update.

2017/05/15 20:01:22 Open log file.
2017/05/15 20:01:22 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 20:02:22 Start replace hosts file.
2017/05/15 20:02:23 Finish:Hosts file Not update.

2017/05/15 20:08:53 Open log file.
2017/05/15 20:08:53 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 20:09:53 Start replace hosts file.
2017/05/15 20:09:54 Finish:Hosts file Not update.

2017/05/15 20:12:03 Open log file.
2017/05/15 20:12:03 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 20:13:03 Start replace hosts file.
2017/05/15 20:13:04 Finish:Hosts file Not update.

2017/05/15 20:43:04 Start replace hosts file.
2017/05/15 20:43:05 Finish:Hosts file Not update.

2017/05/15 21:07:38 Open log file.
2017/05/15 21:07:38 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/15 21:08:38 Start replace hosts file.
2017/05/15 21:08:39 Finish:Hosts file Not update.

2017/05/15 21:38:39 Start replace hosts file.
2017/05/15 21:38:40 Finish:Hosts file Not update.

2017/05/15 22:08:40 Start replace hosts file.
2017/05/15 22:08:44 Finish:Hosts file Not update.

2017/05/15 22:38:44 Start replace hosts file.
2017/05/15 22:38:45 Finish:Hosts file Not update.

2017/05/15 23:08:45 Start replace hosts file.
2017/05/15 23:08:46 Finish:Hosts file Not update.

2017/05/15 23:38:46 Start replace hosts file.
2017/05/15 23:38:47 Finish:Hosts file Not update.

2017/05/16 00:08:47 Start replace hosts file.
2017/05/16 00:08:49 Finish:Hosts file Not update.

2017/05/16 08:41:22 Open log file.
2017/05/16 08:41:22 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/16 08:42:22 Start replace hosts file.
2017/05/16 08:42:24 Finish:Hosts file Not update.

2017/05/16 09:12:24 Start replace hosts file.
2017/05/16 09:12:24 Finish:Hosts file Not update.

2017/05/16 09:42:24 Start replace hosts file.
2017/05/16 09:42:25 Finish:Hosts file Not update.

2017/05/16 10:12:25 Start replace hosts file.
2017/05/16 10:12:26 Finish:Hosts file Not update.

2017/05/16 10:42:26 Start replace hosts file.
2017/05/16 10:42:26 Finish:Hosts file Not update.

2017/05/16 11:12:26 Start replace hosts file.
2017/05/16 11:12:27 Finish:Hosts file Not update.

2017/05/16 17:08:40 Open log file.
2017/05/16 17:08:40 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/05/16 17:09:40 Start replace hosts file.
2017/05/16 17:09:41 Finish:Hosts file Not update.

2017/07/28 20:59:24 Open log file.
2017/07/28 20:59:24 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/07/28 21:00:24 Start replace hosts file.
2017/07/28 21:01:48 Fatal Error:
                    DownLoad hosts file Error! (GetLastError():183)
                    Please contact the application's support team for more information.
2017/07/29 09:26:37 Open log file.
2017/07/29 09:26:37 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/07/29 09:27:37 Start replace hosts file.
2017/07/29 09:27:38 Finish:Hosts file Not update.

2017/07/29 09:55:43 Open log file.
2017/07/29 09:57:38 Start replace hosts file.
2017/07/29 09:59:45 Open log file.
2017/07/29 09:59:45 LICENSE:General Public License
                    Copyright (C) 2016 Too-Naive
                    Bug report:[hidden]
                               Or open new issue.(https://github.com/HostsTools/Windows)
2017/07/29 10:00:45 Start replace hosts file.

**Comment by ghost** [comment]
请问这是怎样。。。
