### ISSUE TITLE
请问怎么静默运行 Tool.exe

### ISSUE THREAD

**Issue by Skylarzz** [HostsTools/Windows#67]
Tool.exe 运行完成后，会弹框提示「修改成功」，请问怎么实现不弹成功提示（仅失败时提示）

**Comment by ghost** [comment]
emmmmmmmmmmmmmmmmmmmmmmmmmmmm 你这样一问 我终于想起以前那个玩意是做什么的了
这两天发个`tool-slient.zip`的包 届时下载即可

**Comment by Skylarzz** [comment]
@Too-Naive 谢谢帮助

话说难道有更好的东东代替吗？我看主页面是推荐使用 Hosts Tool 的？

**Comment by Skylarzz** [comment]
主要是不习惯安装服务，尽量用一个脚本来控制各种自启软件了

**Comment by ghost** [comment]
没事....开学了...不小心放鸽子了 今天给他搞定好了Orz

**Comment by Skylarzz** [comment]
谢谢，是 2.1.19 那个吗
