### ISSUE TITLE
打开tool.exe提示找不到dll文件

### ISSUE THREAD

**Issue by USYDmatt** [HostsTools/Windows#74]
提示系统缺失libstdc++-6.dll与libgcc_sdw2-1.dll文件，无法继续执行代码。
尝试安装VC++运行库并且将这两个dll文件补全之后，再次打开程序提示应用程序无法正常启动（0x000007b）.
能否告知如何处理？谢谢

**Comment by ghost** [comment]
执行先前的版本是否有出现同样的情况？我本地更换了编译器，如果没有出现同样情况的话应该是我本地编译器的版本问题。

**Comment by USYDmatt** [comment]
执行2.2.0版本不会出现这个问题
但是发现更新完hosts在我的网络环境下依然打不开G

**Comment by ghost** [comment]
打不开是因为 googlehosts/hosts#64
那应该就是编译器的问题 稍后我重新编译

**Comment by USYDmatt** [comment]
谢谢

**Comment by yduke** [comment]
same here
"The program cant't start because libgcc_s_dw2-1.dll is missing from your computer. Try to reinstalling the program to fix this problem."

**Comment by ghost** [comment]
现在应该修复了
