### ISSUE TITLE
更新hosts无法使用

### ISSUE THREAD

**Issue by HuangGuigui** [HostsTools/Windows#75]
今天下载了tools以后按照提示更新，但是很多网站依旧无法打开。对于电脑来说我就是一个纯小白级别的用户。但是由于工作需要本人经常要用到谷歌学术这个网站。请问要如何才能使用您提供的TOOLS程序更新hosts可以登陆谷歌。如果方便的话希望能够留下一个方便联系的练习方式。谢谢。如果可以帮我解决，小弟会有感谢。真诚地期待你的回复练习

**Comment by ghost** [comment]
Redirect to [google hosts](https://github.com/googlehosts/hosts)

**Comment by HuangGuigui** [comment]
关于你回复的问题具体情况是这样。麻烦您看一下我在电脑上的截图。。这是我在使用的时候发生的情况
![qq 20180223185202](https://user-images.githubusercontent.com/33273326/36590799-cb561fd8-18ca-11e8-8ea3-94f2683763d8.jpg)
![qq 20180223185211](https://user-images.githubusercontent.com/33273326/36590800-cbc4165a-18ca-11e8-81a3-7ddaa8c0b10d.jpg)
而且在使用以后我的系统hosts文件里虽然有新的hosts文件，但是除了雅虎的功能能够使用以外。Google所有服务都无法使用。。请问要如何按照你说的重新定向到谷歌主机。由于本人是纯小白。所以很多问题几乎都不懂。目前只能使用SS。所以希望您能够不嫌弃教我一下

**Comment by ghost** [comment]
无法使用不是软件的问题啦，本软件只用于方便的更新 hosts 而不对 hosts 是否能够使用负责。
