### ISSUE TITLE
如何设置下载频率

### ISSUE THREAD

**Issue by chaozhao** [HostsTools/Windows#79]
hostsTools已经作为服务在系统中运行，每天都自动下载数个文件，可以自己设置下载频率吗，比如一周，两周一次就够了

**Comment by ghost** [comment]
这个 特殊要求的话要重新编译 暂时无设定功能
如确实有需要的话我可以帮您重新编译一份

**Comment by chaozhao** [comment]
那就麻烦了 帮我编译一份7天 下载一次的 谢谢了 能给我发邮件吗

**Comment by ghost** [comment]
您电脑是一直开着吗 不然它不能7天 check 一次噢XDD
我会放在这个 issue 的附件里面 或者给你链接

**Comment by chaozhao** [comment]
公司的电脑 就让他周一9点开始下载吧

**Comment by ghost** [comment]
那其实....您可以手动改成计划任务来执行 不用安装服务 计划任务配置一下就好了

**Comment by chaozhao** [comment]
哦 也好 谢谢了
